import type { GearInfo } from "../types";

const GEAR: GearInfo[] = [
  {
    name: "Pole",
    cost: { gp: 0, sp: 5, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
    l10n: { name: "長竿" },
  },
  {
    name: "Rope, 60'",
    cost: { gp: 1, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
    l10n: { name: "繩索 (60呎)" },
  },
  {
    name: "Oil, Flask",
    cost: { gp: 0, sp: 5, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
    l10n: { name: "油 (瓶)" },
  },
  {
    name: "Light Spell (Double Range)",
    cost: { gp: 0, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 1 },
    l10n: { name: "光亮術 (雙倍範圍)" },
  },
  {
    name: "Iron Spikes",
    cost: { gp: 1, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 10, slotsUsed: 1, freeCarry: 0 },
    l10n: { name: "鐵釘" },
  },
  {
    name: "Flint and Steel",
    cost: { gp: 0, sp: 5, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
    l10n: { name: "打火石與火鐮" },
  },
  {
    name: "Mirror",
    cost: { gp: 10, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
    l10n: { name: "鏡子" },
  },
  {
    name: "Rations",
    cost: { gp: 0, sp: 5, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 3, slotsUsed: 1, freeCarry: 0 },
    l10n: { name: "口糧" },
  },
  {
    name: "Crowbar",
    cost: { gp: 0, sp: 5, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
    l10n: { name: "撬棍" },
  },
  {
    name: "Light Spell",
    cost: { gp: 0, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 1 },
    l10n: { name: "光亮術" },
  },
  {
    name: "Caltrops",
    cost: { gp: 0, sp: 5, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
    l10n: { name: "鐵蒺藜" },
  },
  {
    name: "Flask",
    cost: { gp: 0, sp: 3, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
    l10n: { name: "扁瓶" },
  },
  {
    name: "Arrows",
    cost: { gp: 1, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 20, slotsUsed: 1, freeCarry: 0 },
    l10n: { name: "箭矢" },
  },
  {
    name: "Bottle",
    cost: { gp: 0, sp: 3, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
    l10n: { name: "瓶子" },
  },
  {
    name: "Grappling Hook",
    cost: { gp: 1, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
    l10n: { name: "爪鉤" },
  },
  {
    name: "Crossbow Bolts",
    cost: { gp: 1, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 20, slotsUsed: 1, freeCarry: 0 },
    l10n: { name: "十字弓矢" },
  },
  {
    name: "Lantern",
    cost: { gp: 5, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
    l10n: { name: "提燈" },
  },
  {
    name: "Thieves' Tools",
    cost: { gp: 0, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 1 },
    l10n: { name: "盜賊工具" },
  },
  {
    name: "Backpack",
    cost: { gp: 2, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 1 },
    l10n: { name: "背包" },
  },
  {
    name: "Light Spell (Double Time)",
    cost: { gp: 0, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 1 },
    l10n: { name: "光亮術 (雙倍時間)" },
  },
  {
    name: "Holy Symbol",
    cost: { gp: 0, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 1 },
    l10n: { name: "聖徽" },
  },
  {
    name: "Torch",
    cost: { gp: 0, sp: 5, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
    l10n: { name: "火把" },
  },
  {
    name: "Thieving Tools",
    cost: { gp: 0, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 0, freeCarry: 1 },
    l10n: { name: "盜賊工具" },
  },
  {
    name: "Holy Symbol",
    cost: { gp: 0, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 0, freeCarry: 1 },
    l10n: { name: "聖徽" },
  },
];

const GEAR_COMPENDIUM: { [name: string]: GearInfo } = {};
for (const g of GEAR) {
  GEAR_COMPENDIUM[g.name.toLowerCase()] = g;
}

export default GEAR_COMPENDIUM;
