import type { GearInfo } from "../types";

export const GEAR: GearInfo[] = [
  {
    name: "Backpack",
    type: "Basic",
    cost: { gp: 2, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: false,
    weight: 5,
    l10n: { name: "背包" },
  },
  {
    name: "Bedroll",
    type: "Basic",
    cost: { gp: 1, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: false,
    weight: 7,
    l10n: { name: "睡袋" },
  },
  {
    name: "Crowbar",
    type: "Basic",
    cost: { gp: 2, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    weight: 5,
    l10n: { name: "撬棍" },
  },
  {
    name: "Hammer",
    type: "Basic",
    cost: { gp: 1, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    weight: 3,
    l10n: { name: "鐵鎚" },
  },
  {
    name: "Healer's Kit",
    type: "Basic",
    cost: { gp: 5, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: false,
    weight: 3,
    l10n: { name: "醫藥箱" },
  },
  {
    name: "Holy Water (flask)",
    type: "Basic",
    cost: { gp: 25, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    weight: 1,
    l10n: { name: "聖水 (瓶)" },
  },
  {
    name: "Lantern, bullseye",
    type: "Basic",
    cost: { gp: 10, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    weight: 2,
    l10n: { name: "靶心提燈" },
  },
  {
    name: "Lantern, hooded",
    type: "Basic",
    cost: { gp: 5, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    weight: 2,
    l10n: { name: "防風提燈" },
  },
  {
    name: "Lock",
    type: "Basic",
    cost: { gp: 10, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: false,
    weight: 1,
    l10n: { name: "鎖" },
  },
  {
    name: "Mess Kit",
    type: "Basic",
    cost: { gp: 0, sp: 2, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: false,
    weight: 1,
    l10n: { name: "餐具組" },
  },
  {
    name: "Oil (flask)",
    type: "Basic",
    cost: { gp: 0, sp: 1, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    weight: 1,
    l10n: { name: "油 (瓶)" },
  },
  {
    name: "Piton",
    type: "Basic",
    cost: { gp: 0, sp: 0, cp: 5, ep: 0, pp: 0 },
    canBeEquipped: false,
    weight: 0.25,
    l10n: { name: "岩釘" },
  },
  {
    name: "Potion of Healing",
    type: "Basic",
    cost: { gp: 50, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    weight: 0.5,
    l10n: { name: "治療藥水" },
  },
  {
    name: "Rations (1 day)",
    type: "Basic",
    cost: { gp: 0, sp: 5, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: false,
    weight: 2,
    l10n: { name: "口糧 (1天份)" },
  },
  {
    name: "Rope, hempen (50 feet)",
    type: "Basic",
    cost: { gp: 1, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: false,
    weight: 10,
    l10n: { name: "麻繩 (50呎)" },
  },
  {
    name: "Rope, silk (50 feet)",
    type: "Basic",
    cost: { gp: 10, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: false,
    weight: 5,
    l10n: { name: "絲繩 (50呎)" },
  },
  {
    name: "Tinderbox",
    type: "Basic",
    cost: { gp: 0, sp: 5, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: false,
    weight: 1,
    l10n: { name: "打火匣" },
  },
  {
    name: "Torch",
    type: "Basic",
    cost: { gp: 0, sp: 0, cp: 1, ep: 0, pp: 0 },
    canBeEquipped: true,
    weight: 1,
    l10n: { name: "火把" },
  },
  {
    name: "Waterskin",
    type: "Basic",
    cost: { gp: 0, sp: 2, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    weight: 5, // full
    l10n: { name: "水袋" },
  },
];

const GEAR_COMPENDIUM: { [name: string]: GearInfo } = {};
for (const g of GEAR) {
  GEAR_COMPENDIUM[g.name.toLowerCase()] = g;
}
export default GEAR_COMPENDIUM;
