import type { WeaponInfo } from "../types";

export const WEAPONS: WeaponInfo[] = [
  // --- Simple Melee ---
  {
    name: "Club",
    type: "Weapon",
    cost: { gp: 0, sp: 1, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Light"],
    range: "5 ft",
    weaponType: "Simple Melee",
    damage: { oneHanded: { diceType: "d4", numDice: 1 }, damageType: "Bludgeoning" },
    weight: 2,
    l10n: { name: "棍棒" },
  },
  {
    name: "Dagger",
    type: "Weapon",
    cost: { gp: 2, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Finesse", "Light", "Thrown"],
    range: "20/60",
    weaponType: "Simple Melee",
    damage: { oneHanded: { diceType: "d4", numDice: 1 }, damageType: "Piercing" },
    weight: 1,
    l10n: { name: "匕首" },
  },
  {
    name: "Greatclub",
    type: "Weapon",
    cost: { gp: 0, sp: 2, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Two-Handed"],
    range: "5 ft",
    weaponType: "Simple Melee",
    damage: { twoHanded: { diceType: "d8", numDice: 1 }, damageType: "Bludgeoning" },
    weight: 10,
    l10n: { name: "巨棒" },
  },
  {
    name: "Handaxe",
    type: "Weapon",
    cost: { gp: 5, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Light", "Thrown"],
    range: "20/60",
    weaponType: "Simple Melee",
    damage: { oneHanded: { diceType: "d6", numDice: 1 }, damageType: "Slashing" },
    weight: 2,
    l10n: { name: "手斧" },
  },
  {
    name: "Javelin",
    type: "Weapon",
    cost: { gp: 0, sp: 5, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Thrown"],
    range: "30/120",
    weaponType: "Simple Melee",
    damage: { oneHanded: { diceType: "d6", numDice: 1 }, damageType: "Piercing" },
    weight: 2,
    l10n: { name: "標槍" },
  },
  {
    name: "Light Hammer",
    type: "Weapon",
    cost: { gp: 2, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Light", "Thrown"],
    range: "20/60",
    weaponType: "Simple Melee",
    damage: { oneHanded: { diceType: "d4", numDice: 1 }, damageType: "Bludgeoning" },
    weight: 2,
    l10n: { name: "輕鎚" },
  },
  {
    name: "Mace",
    type: "Weapon",
    cost: { gp: 5, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: [],
    range: "5 ft",
    weaponType: "Simple Melee",
    damage: { oneHanded: { diceType: "d6", numDice: 1 }, damageType: "Bludgeoning" },
    weight: 4,
    l10n: { name: "釘頭錘" },
  },
  {
    name: "Quarterstaff",
    type: "Weapon",
    cost: { gp: 0, sp: 2, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Versatile"],
    range: "5 ft",
    weaponType: "Simple Melee",
    damage: {
      oneHanded: { diceType: "d6", numDice: 1 },
      twoHanded: { diceType: "d8", numDice: 1 },
      damageType: "Bludgeoning"
    },
    weight: 4,
    l10n: { name: "長棍" },
  },
  {
    name: "Sickle",
    type: "Weapon",
    cost: { gp: 1, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Light"],
    range: "5 ft",
    weaponType: "Simple Melee",
    damage: { oneHanded: { diceType: "d4", numDice: 1 }, damageType: "Slashing" },
    weight: 2,
    l10n: { name: "鐮刀" },
  },
  {
    name: "Spear",
    type: "Weapon",
    cost: { gp: 1, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Thrown", "Versatile"],
    range: "20/60",
    weaponType: "Simple Melee",
    damage: {
      oneHanded: { diceType: "d6", numDice: 1 },
      twoHanded: { diceType: "d8", numDice: 1 },
      damageType: "Piercing"
    },
    weight: 3,
    l10n: { name: "矛" },
  },

  // --- Simple Ranged ---
  {
    name: "Crossbow, light",
    type: "Weapon",
    cost: { gp: 25, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Ammunition", "Loading", "Two-Handed"],
    range: "80/320",
    weaponType: "Simple Ranged",
    damage: { twoHanded: { diceType: "d8", numDice: 1 }, damageType: "Piercing" },
    weight: 5,
    l10n: { name: "輕型十字弓" },
  },
  {
    name: "Dart",
    type: "Weapon",
    cost: { gp: 0, sp: 0, cp: 5, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Finesse", "Thrown"],
    range: "20/60",
    weaponType: "Simple Ranged",
    damage: { oneHanded: { diceType: "d4", numDice: 1 }, damageType: "Piercing" },
    weight: 0.25,
    l10n: { name: "飛鏢" },
  },
  {
    name: "Shortbow",
    type: "Weapon",
    cost: { gp: 25, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Ammunition", "Two-Handed"],
    range: "80/320",
    weaponType: "Simple Ranged",
    damage: { twoHanded: { diceType: "d6", numDice: 1 }, damageType: "Piercing" },
    weight: 2,
    l10n: { name: "短弓" },
  },
  {
    name: "Sling",
    type: "Weapon",
    cost: { gp: 0, sp: 1, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Ammunition"],
    range: "30/120",
    weaponType: "Simple Ranged",
    damage: { oneHanded: { diceType: "d4", numDice: 1 }, damageType: "Bludgeoning" },
    weight: 0,
    l10n: { name: "投石索" },
  },

  // --- Martial Melee ---
  {
    name: "Battleaxe",
    type: "Weapon",
    cost: { gp: 10, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Versatile"],
    range: "5 ft",
    weaponType: "Martial Melee",
    damage: {
      oneHanded: { diceType: "d8", numDice: 1 },
      twoHanded: { diceType: "d10", numDice: 1 },
      damageType: "Slashing"
    },
    weight: 4,
    l10n: { name: "戰斧" },
  },
  {
    name: "Flail",
    type: "Weapon",
    cost: { gp: 10, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: [],
    range: "5 ft",
    weaponType: "Martial Melee",
    damage: { oneHanded: { diceType: "d8", numDice: 1 }, damageType: "Bludgeoning" },
    weight: 2,
    l10n: { name: "連枷" },
  },
  {
    name: "Glaive",
    type: "Weapon",
    cost: { gp: 20, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Heavy", "Reach", "Two-Handed"],
    range: "10 ft",
    weaponType: "Martial Melee",
    damage: { twoHanded: { diceType: "d10", numDice: 1 }, damageType: "Slashing" },
    weight: 6,
    l10n: { name: "關刀" },
  },
  {
    name: "Greataxe",
    type: "Weapon",
    cost: { gp: 30, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Heavy", "Two-Handed"],
    range: "5 ft",
    weaponType: "Martial Melee",
    damage: { twoHanded: { diceType: "d12", numDice: 1 }, damageType: "Slashing" },
    weight: 7,
    l10n: { name: "巨斧" },
  },
  {
    name: "Greatsword",
    type: "Weapon",
    cost: { gp: 50, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Heavy", "Two-Handed"],
    range: "5 ft",
    weaponType: "Martial Melee",
    damage: { twoHanded: { diceType: "d6", numDice: 2 }, damageType: "Slashing" },
    weight: 6,
    l10n: { name: "巨劍" },
  },
  {
    name: "Halberd",
    type: "Weapon",
    cost: { gp: 20, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Heavy", "Reach", "Two-Handed"],
    range: "10 ft",
    weaponType: "Martial Melee",
    damage: { twoHanded: { diceType: "d10", numDice: 1 }, damageType: "Slashing" },
    weight: 6,
    l10n: { name: "長戟" },
  },
  {
    name: "Lance",
    type: "Weapon",
    cost: { gp: 10, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Reach", "Special"],
    range: "10 ft",
    weaponType: "Martial Melee",
    damage: { oneHanded: { diceType: "d12", numDice: 1 }, damageType: "Piercing" },
    weight: 6,
    l10n: { name: "騎槍" },
  },
  {
    name: "Longsword",
    type: "Weapon",
    cost: { gp: 15, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Versatile"],
    range: "5 ft",
    weaponType: "Martial Melee",
    damage: {
      oneHanded: { diceType: "d8", numDice: 1 },
      twoHanded: { diceType: "d10", numDice: 1 },
      damageType: "Slashing"
    },
    weight: 3,
    l10n: { name: "長劍" },
  },
  {
    name: "Maul",
    type: "Weapon",
    cost: { gp: 10, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Heavy", "Two-Handed"],
    range: "5 ft",
    weaponType: "Martial Melee",
    damage: { twoHanded: { diceType: "d6", numDice: 2 }, damageType: "Bludgeoning" },
    weight: 10,
    l10n: { name: "巨鎚" },
  },
  {
    name: "Morningstar",
    type: "Weapon",
    cost: { gp: 15, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: [],
    range: "5 ft",
    weaponType: "Martial Melee",
    damage: { oneHanded: { diceType: "d8", numDice: 1 }, damageType: "Piercing" },
    weight: 4,
    l10n: { name: "晨星鎚" },
  },
  {
    name: "Pike",
    type: "Weapon",
    cost: { gp: 5, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Heavy", "Reach", "Two-Handed"],
    range: "10 ft",
    weaponType: "Martial Melee",
    damage: { twoHanded: { diceType: "d10", numDice: 1 }, damageType: "Piercing" },
    weight: 18,
    l10n: { name: "長矛" },
  },
  {
    name: "Rapier",
    type: "Weapon",
    cost: { gp: 25, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Finesse"],
    range: "5 ft",
    weaponType: "Martial Melee",
    damage: { oneHanded: { diceType: "d8", numDice: 1 }, damageType: "Piercing" },
    weight: 2,
    l10n: { name: "刺劍" },
  },
  {
    name: "Scimitar",
    type: "Weapon",
    cost: { gp: 25, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Finesse", "Light"],
    range: "5 ft",
    weaponType: "Martial Melee",
    damage: { oneHanded: { diceType: "d6", numDice: 1 }, damageType: "Slashing" },
    weight: 3,
    l10n: { name: "彎刀" },
  },
  {
    name: "Shortsword",
    type: "Weapon",
    cost: { gp: 10, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Finesse", "Light"],
    range: "5 ft",
    weaponType: "Martial Melee",
    damage: { oneHanded: { diceType: "d6", numDice: 1 }, damageType: "Piercing" },
    weight: 2,
    l10n: { name: "短劍" },
  },
  {
    name: "Trident",
    type: "Weapon",
    cost: { gp: 5, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Thrown", "Versatile"],
    range: "20/60",
    weaponType: "Martial Melee",
    damage: {
      oneHanded: { diceType: "d6", numDice: 1 },
      twoHanded: { diceType: "d8", numDice: 1 },
      damageType: "Piercing"
    },
    weight: 4,
    l10n: { name: "三叉戟" },
  },
  {
    name: "War Pick",
    type: "Weapon",
    cost: { gp: 5, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: [],
    range: "5 ft",
    weaponType: "Martial Melee",
    damage: { oneHanded: { diceType: "d8", numDice: 1 }, damageType: "Piercing" },
    weight: 2,
    l10n: { name: "戰鎬" },
  },
  {
    name: "Warhammer",
    type: "Weapon",
    cost: { gp: 15, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Versatile"],
    range: "5 ft",
    weaponType: "Martial Melee",
    damage: {
      oneHanded: { diceType: "d8", numDice: 1 },
      twoHanded: { diceType: "d10", numDice: 1 },
      damageType: "Bludgeoning"
    },
    weight: 2,
    l10n: { name: "戰鎚" },
  },
  {
    name: "Whip",
    type: "Weapon",
    cost: { gp: 2, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Finesse", "Reach"],
    range: "10 ft",
    weaponType: "Martial Melee",
    damage: { oneHanded: { diceType: "d4", numDice: 1 }, damageType: "Slashing" },
    weight: 3,
    l10n: { name: "鞭子" },
  },

  // --- Martial Ranged ---
  {
    name: "Blowgun",
    type: "Weapon",
    cost: { gp: 10, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Ammunition", "Loading"],
    range: "25/100",
    weaponType: "Martial Ranged",
    damage: { oneHanded: { diceType: "d4", numDice: 1 }, damageType: "Piercing" }, // Usually 1 dmg, but standardizing to d4 for simplicity or d1? using d4 is fine for now
    weight: 1,
    l10n: { name: "吹箭筒" },
  },
  {
    name: "Crossbow, hand",
    type: "Weapon",
    cost: { gp: 75, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Ammunition", "Light", "Loading"],
    range: "30/120",
    weaponType: "Martial Ranged",
    damage: { oneHanded: { diceType: "d6", numDice: 1 }, damageType: "Piercing" },
    weight: 3,
    l10n: { name: "手弩" },
  },
  {
    name: "Crossbow, heavy",
    type: "Weapon",
    cost: { gp: 50, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Ammunition", "Heavy", "Loading", "Two-Handed"],
    range: "100/400",
    weaponType: "Martial Ranged",
    damage: { twoHanded: { diceType: "d10", numDice: 1 }, damageType: "Piercing" },
    weight: 18,
    l10n: { name: "重型十字弓" },
  },
  {
    name: "Longbow",
    type: "Weapon",
    cost: { gp: 50, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Ammunition", "Heavy", "Two-Handed"],
    range: "150/600",
    weaponType: "Martial Ranged",
    damage: { twoHanded: { diceType: "d8", numDice: 1 }, damageType: "Piercing" },
    weight: 2,
    l10n: { name: "長弓" },
  },
  {
    name: "Net",
    type: "Weapon",
    cost: { gp: 1, sp: 0, cp: 0, ep: 0, pp: 0 },
    canBeEquipped: true,
    properties: ["Special", "Thrown"],
    range: "5/15",
    weaponType: "Martial Ranged",
    damage: { oneHanded: { diceType: "d4", numDice: 0 } }, // No damage
    weight: 3,
    l10n: { name: "網" },
  },
];

const WEAPON_COMPENDIUM: { [name: string]: WeaponInfo } = {};
for (const w of WEAPONS) {
  WEAPON_COMPENDIUM[w.name.toLowerCase()] = w;
}
export default WEAPON_COMPENDIUM;
